<a href="https://colab.research.google.com/github/princepatel2004/Edunet-Summer-Intership-/blob/main/%5BDay_4%5D_09_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Day-4 09-07-26

# Add dataset to python file

In [3]:
import pandas as pd

df = pd.read_csv("/renewable_energy_dataset.csv")

In [4]:
df.head()

,State,Year,Installed - Bio-Mass Power,Installed - Small Hydro Power,Installed - Solar Power,Installed - Wind Power,Zone,Installed - Waste to Energy,Population,GSDP (crore INR)
0,Andaman And Nicobar Islands,2006,0.0,5.25,0.1,0.0,South,0.0,366589.0,3114.06
1,Andaman And Nicobar Islands,2007,0.0,5.25,0.1,1.1,South,0.0,369517.0,3114.06
2,Andaman And Nicobar Islands,2008,0.0,5.25,0.1,1.1,South,0.0,372344.0,3114.06
3,Andaman And Nicobar Islands,2009,0.0,5.25,0.1,0.0,South,0.0,375072.0,3114.06
4,Andaman And Nicobar Islands,2010,0.0,5.25,0.1,0.0,South,0.0,377699.0,3114.06

In [5]:
df.shape
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   State                          100 non-null    object
 1   Year                           100 non-null    int64
 2   Installed - Bio-Mass Power     100 non-null    float64
 3   Installed - Small Hydro Power  100 non-null    float64
 4   Installed - Solar Power        97 non-null     float64
 5   Installed - Wind Power         97 non-null     float64
 6   Zone                           100 non-null    object
 7   Installed - Waste to Energy    100 non-null    float64
 8   Population                     97 non-null     float64
 9   GSDP (crore INR)               100 non-null    float64
dtypes: float64(7), int64(1), object(2)
memory usage: 7.9+ KB

# Feature Description

State - Name of the Indian State.

Year - Year in which the data was recorded.

Installed - Bio-Mass Power - Biomass energy generation capacity.

Installed - Small Hydro Power - Small hydro power generation capacity.

Installed - Solar Power - Installed solar power capacity.

Installed - Wind Power - Installed wind power capacity.

Zone - Geographical zone of India.

Installed - Waste to Energy - Energy generated from waste.

Population - Population of the state.

GSDP (crore INR) - Gross State Domestic Product.

# General Observations

• Population generally increases every year.

• Solar capacity has increased over the years.

• Wind power is higher in coastal states.

• Waste-to-energy capacity is comparatively lower.

• Different renewable sources contribute differently depending on the state.

# Check null values

In [6]:
df.isnull().sum()

State                            0
Year                             0
Installed - Bio-Mass Power       0
Installed - Small Hydro Power    0
Installed - Solar Power          3
Installed - Wind Power           3
Zone                             0
Installed - Waste to Energy      0
Population                       3
GSDP (crore INR)                 0
dtype: int64

# Fill null values with mean of cloumn

In [8]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df.isnull().sum()

State                            0
Year                             0
Installed - Bio-Mass Power       0
Installed - Small Hydro Power    0
Installed - Solar Power          0
Installed - Wind Power           0
Zone                             0
Installed - Waste to Energy      0
Population                       0
GSDP (crore INR)                 0
dtype: int64

In [9]:
print("Average Solar Power :", df["Installed - Solar Power"].mean())

print("Average Wind Power :", df["Installed - Wind Power"].mean())

print("Average Biomass Power :", df["Installed - Bio-Mass Power"].mean())

print("Average Small Hydro :", df["Installed - Small Hydro Power"].mean())

Average Solar Power : 434.2172651944367
Average Wind Power : 377.8605537866642
Average Biomass Power : 90.7092606564598
Average Small Hydro : 68.59183815709687

# Summary

In today's task, I imported a renewable energy dataset using pandas.

I explored the dataset using various pandas functions such as head(), shape(), columns(), and info()

I study the relationship btw different column like population, GSDP and renewable energy capacities.

Missing values were identified using isnull() and handled using fillna() by replacing them with the mean of the respective numerical columns.